web:
  build: .
  command: npm start
  environment:
    EXPRESS_PORT: 5000
  ports:
   - "5000:5000"
  volumes:
   - .:/code
  links:
   - redis
   - mongo
redis:
  image: redis
mongo:
  image: mongo
